import { Project } from "./types";

export const sampleProject: Project = {
  name: "Website Redesign",
  description: "Redesign the company website with modern UI",
  tasks: [
    {
      id: "1",
      title: "Design system setup",
      description: "Create color palette, typography, and spacing tokens",
      status: "done",
      priority: "high",
      assignee: "Alice",
      tags: ["design"],
    },
    {
      id: "2",
      title: "Homepage wireframe",
      description: "Create wireframes for the new homepage layout",
      status: "done",
      priority: "high",
      assignee: "Bob",
      tags: ["design", "homepage"],
    },
    {
      id: "3",
      title: "Build navigation component",
      description: "Implement responsive nav with mobile menu",
      status: "in-progress",
      priority: "high",
      assignee: "Charlie",
      tags: ["frontend"],
    },
    {
      id: "4",
      title: "Hero section",
      description: "Build the hero section with animated background",
      status: "in-progress",
      priority: "medium",
      assignee: "Alice",
      tags: ["frontend", "homepage"],
    },
    {
      id: "5",
      title: "API integration",
      description: "Connect the contact form to the backend API",
      status: "todo",
      priority: "medium",
      assignee: "Charlie",
      tags: ["backend"],
    },
    {
      id: "6",
      title: "Footer component",
      description: "Create footer with links, social icons, and newsletter signup",
      status: "todo",
      priority: "low",
      assignee: "Bob",
      tags: ["frontend"],
    },
    {
      id: "7",
      title: "Performance audit",
      description: "Run Lighthouse and optimize Core Web Vitals",
      status: "todo",
      priority: "medium",
      tags: ["devops"],
    },
    {
      id: "8",
      title: "SEO optimization",
      description: "Add meta tags, structured data, and sitemap",
      status: "todo",
      priority: "low",
      tags: ["seo"],
    },
    {
      id: "9",
      title: "Testimonials section",
      description: "Build carousel for customer testimonials",
      status: "in-progress",
      priority: "low",
      assignee: "Bob",
      tags: ["frontend", "homepage"],
    },
  ],
};

export const navItems = [
  { label: "Dashboard", icon: "grid", active: true },
  { label: "Projects", icon: "folder" },
  { label: "Calendar", icon: "calendar" },
  { label: "Team", icon: "users" },
  { label: "Settings", icon: "settings" },
];
